Repository 2Abendsegler/GClh, pull requests merged in 2022-12, with the labels that each got.

#2247 [Cache listing] Show who gave a favorite in cache listings
  gc_little_helper_II.user.js
Labels: enhancement, status: in progress

#2249 [Cache Listing] Show who gave a favorite in cache listings
  gc_little_helper_II.user.js
Labels: status: completed, improvement

#2248 [COD] Link to CCE are undefined
  gc_little_helper_II.user.js
Labels: bug, status: wait for merge
