Repository 2Abendsegler/GClh, pull requests merged in 2025-01, with the labels that each got.

#2681 Dashboard] Favorites icon almost completely disappears behind the found icon.
  gc_little_helper_II.user.js
Labels: bug

#2691 [Search Map] Temporarily deactivate not corrected parts
  gc_little_helper_II.user.js
Labels: bug

#2687 [Log Form] Added placeholder cache type to signature and log templates
  gc_little_helper_II.user.js
Labels: enhancement

#2692 [Log Form] Added placeholder cache type to signature and log templates
  gc_little_helper_II.user.js
Labels: enhancement

#2693 [Cache Listing] The log totals icons at the top are missing and above the logs the log totals icons are displayed incorrectly.
  gc_little_helper_II.user.js
Labels: bug

#2694 [Browse Map] The log totals icons are displayed incorrectly in the detailed cache information.
  gc_little_helper_II.user.js
Labels: bug

#2696 FAQ developer mode in chrome-based browser and conflict with add-on GeocachingUtils
  docu/faq.md
Labels: documentation
